<?php

/**
 * @method staticboolean accepted($value)
 * @method staticboolean alpha($value, $unicode)
 * @method staticboolean alphanum($value, $unicode)
 * @method staticboolean between($value, $min, $max)
 * @method staticboolean contains($value, $needle)
 * @method staticboolean date($value, $operator, $test)
 * @method staticboolean denied($value)
 * @method staticboolean different($value, $other, $strict)
 * @method staticboolean email($value)
 * @method staticboolean empty($value)
 * @method staticboolean endsWith($value, $end)
 * @method staticboolean filename($value)
 * @method staticboolean in($value, $in, $strict)
 * @method staticboolean integer($value, $strict)
 * @method staticboolean ip($value)
 * @method staticboolean json($value)
 * @method staticboolean less($value, $max)
 * @method staticboolean match($value, $pattern)
 * @method staticboolean max($value, $max)
 * @method staticboolean min($value, $min)
 * @method staticboolean maxLength($value, $max)
 * @method staticboolean minLength($value, $min)
 * @method staticboolean maxWords($value, $max)
 * @method staticboolean minWords($value, $min)
 * @method staticboolean more($value, $min)
 * @method staticboolean notContains($value, $needle)
 * @method staticboolean notEmpty($value)
 * @method staticboolean notIn($value, $notIn)
 * @method staticboolean num($value)
 * @method staticboolean required($value, $array)
 * @method staticboolean same($value, $other, $strict)
 * @method staticboolean size($value, $size, $operator)
 * @method staticboolean startsWith($value, $start)
 * @method staticboolean time($value)
 * @method staticboolean url($value)
 * @method staticboolean uuid($value, $type)
 */
class V {}
